/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;

import java.awt.Color;
import java.awt.Toolkit;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Fachridan Tio Mu'afa
 */
public class Aplikasi extends javax.swing.JFrame {

    /**
     * Creates new form Aplikasi
     */
    private DateTimeFormatter dtf;
    private LocalDateTime WaktuDaftar;

    int tailSenin = 0;
    int tailSelasa = 0;
    int tailRabu = 0;
    int tailKamis = 0;
    int tailJumat = 0;
    int tail = 0;
    int head = 0;
    int size = 11;
    String dataSenin[] = new String[size];
    String dataSelasa[] = new String[size];
    String dataRabu[] = new String[size];
    String dataKamis[] = new String[size];
    String dataJumat[] = new String[size];

    public Aplikasi() {
        initComponents();
        setIcon();
    }

    public boolean isEmpty(int tailHari) {
        this.tail = tailHari;
        if (tail == 0 && head == 0) {
            return true;
        } else {
            return false;
        }
    }

    public boolean isFull(int tailHari) {
        this.tail = tailHari;
        if (tail == size - 1) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        btnLoginPenduduk = new javax.swing.JButton();
        btnLoginOperator = new javax.swing.JButton();
        lblArtboard = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        pnlHomeLogin = new javax.swing.JPanel();
        lblHomeLogin = new javax.swing.JLabel();
        pnlLoginPenduduk = new javax.swing.JPanel();
        btnSubmitPenduduk = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        txtNIK = new javax.swing.JTextField();
        lblLoginPenduduk = new javax.swing.JLabel();
        pnlLoginOperator = new javax.swing.JPanel();
        btnSubmitOperator = new javax.swing.JButton();
        txtOperator = new javax.swing.JTextField();
        pwOperator = new javax.swing.JPasswordField();
        lblLoginOperator = new javax.swing.JLabel();
        pnlLoaderPenduduk = new javax.swing.JPanel();
        lblLoadingPenduduk = new javax.swing.JLabel();
        lblLoaderPenduduk = new javax.swing.JLabel();
        pnlMenuPenduduk = new javax.swing.JPanel();
        btnKK = new javax.swing.JButton();
        btnKTP = new javax.swing.JButton();
        btnAboutPenduduk = new javax.swing.JButton();
        btnLogoutPenduduk = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        lblNIK = new javax.swing.JLabel();
        lblArtBoardPenduduk = new javax.swing.JLabel();
        pnlDashboardPenduduk = new javax.swing.JPanel();
        pnlHomePenduduk = new javax.swing.JPanel();
        lblHome1 = new javax.swing.JLabel();
        pnlKTP = new javax.swing.JPanel();
        btnSenin = new javax.swing.JButton();
        btnRabu = new javax.swing.JButton();
        btnJumat = new javax.swing.JButton();
        lblKTP = new javax.swing.JLabel();
        pnlKK = new javax.swing.JPanel();
        btnSelasa = new javax.swing.JButton();
        btnKamis = new javax.swing.JButton();
        lblKK = new javax.swing.JLabel();
        pnlAboutPenduduk = new javax.swing.JPanel();
        lblAboutPenduduk = new javax.swing.JLabel();
        pnlLoaderOperator = new javax.swing.JPanel();
        lblLoadingOperator = new javax.swing.JLabel();
        lblLoaderOperator = new javax.swing.JLabel();
        pnlMenuOperator = new javax.swing.JPanel();
        btnAboutOperator = new javax.swing.JButton();
        btnLogoutOperator = new javax.swing.JButton();
        lblOP = new javax.swing.JLabel();
        lblArtboardOperator = new javax.swing.JLabel();
        pnlDashboardOperator = new javax.swing.JPanel();
        pnlPanggilan = new javax.swing.JPanel();
        cmbNamaHari = new javax.swing.JComboBox();
        btnPanggil = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        listArray = new javax.swing.JList();
        lblPanggilan = new javax.swing.JLabel();
        pnlAboutOperator = new javax.swing.JPanel();
        lblAboutOperator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Villager");
        setResizable(false);
        setSize(new java.awt.Dimension(652, 492));
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLoginPenduduk.setBackground(new java.awt.Color(126, 7, 243));
        btnLoginPenduduk.setBorder(null);
        btnLoginPenduduk.setContentAreaFilled(false);
        btnLoginPenduduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginPenduduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginPendudukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginPendudukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginPendudukMouseExited(evt);
            }
        });
        btnLoginPenduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPendudukActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLoginPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 40));

        btnLoginOperator.setBackground(new java.awt.Color(126, 7, 243));
        btnLoginOperator.setToolTipText("");
        btnLoginOperator.setBorder(null);
        btnLoginOperator.setContentAreaFilled(false);
        btnLoginOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginOperator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginOperatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginOperatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginOperatorMouseExited(evt);
            }
        });
        pnlLogin.add(btnLoginOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 40));

        lblArtboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Artboard.png"))); // NOI18N
        pnlLogin.add(lblArtboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        pnlDashboard.setLayout(new java.awt.CardLayout());

        pnlHomeLogin.setBackground(new java.awt.Color(126, 7, 243));
        pnlHomeLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHomeLogin.setBackground(new java.awt.Color(126, 7, 243));
        lblHomeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Awal.png"))); // NOI18N
        pnlHomeLogin.add(lblHomeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pnlDashboard.add(pnlHomeLogin, "card1");

        pnlLoginPenduduk.setBackground(new java.awt.Color(126, 7, 243));
        pnlLoginPenduduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitPenduduk.setBackground(new java.awt.Color(126, 7, 243));
        btnSubmitPenduduk.setBorder(null);
        btnSubmitPenduduk.setContentAreaFilled(false);
        btnSubmitPenduduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmitPenduduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitPendudukMouseClicked(evt);
            }
        });
        pnlLoginPenduduk.add(btnSubmitPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 120, 30));

        txtNama.setBackground(new java.awt.Color(230, 231, 232));
        txtNama.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(69, 73, 74));
        txtNama.setText("Nama Lengkap");
        txtNama.setBorder(null);
        txtNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNama.setPreferredSize(new java.awt.Dimension(140, 30));
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaFocusLost(evt);
            }
        });
        pnlLoginPenduduk.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        txtNIK.setBackground(new java.awt.Color(230, 231, 232));
        txtNIK.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        txtNIK.setForeground(new java.awt.Color(69, 73, 74));
        txtNIK.setText("NIK");
        txtNIK.setBorder(null);
        txtNIK.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNIK.setPreferredSize(new java.awt.Dimension(140, 30));
        txtNIK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNIKFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNIKFocusLost(evt);
            }
        });
        pnlLoginPenduduk.add(txtNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 140, 30));

        lblLoginPenduduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LoginPenduduk.png"))); // NOI18N
        lblLoginPenduduk.setText("jLabel1");
        pnlLoginPenduduk.add(lblLoginPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pnlDashboard.add(pnlLoginPenduduk, "card2");

        pnlLoginOperator.setBackground(new java.awt.Color(126, 7, 243));
        pnlLoginOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitOperator.setBackground(new java.awt.Color(126, 7, 243));
        btnSubmitOperator.setBorder(null);
        btnSubmitOperator.setContentAreaFilled(false);
        btnSubmitOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmitOperator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitOperatorMouseClicked(evt);
            }
        });
        pnlLoginOperator.add(btnSubmitOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 120, 30));

        txtOperator.setBackground(new java.awt.Color(255, 255, 255));
        txtOperator.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        txtOperator.setForeground(new java.awt.Color(69, 73, 74));
        txtOperator.setText("Username");
        txtOperator.setBorder(null);
        txtOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtOperator.setPreferredSize(new java.awt.Dimension(165, 25));
        txtOperator.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOperatorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOperatorFocusLost(evt);
            }
        });
        pnlLoginOperator.add(txtOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 180, 30));

        pwOperator.setBackground(new java.awt.Color(255, 255, 255));
        pwOperator.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        pwOperator.setForeground(new java.awt.Color(69, 73, 74));
        pwOperator.setText("Password");
        pwOperator.setToolTipText("");
        pwOperator.setBorder(null);
        pwOperator.setPreferredSize(new java.awt.Dimension(165, 25));
        pwOperator.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwOperatorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwOperatorFocusLost(evt);
            }
        });
        pnlLoginOperator.add(pwOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 180, 30));

        lblLoginOperator.setBackground(new java.awt.Color(126, 7, 243));
        lblLoginOperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LoginOperator.png"))); // NOI18N
        pnlLoginOperator.add(lblLoginOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pnlDashboard.add(pnlLoginOperator, "card3");

        pnlLogin.add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 460, 480));

        getContentPane().add(pnlLogin, "card1");

        pnlLoaderPenduduk.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoaderPenduduk.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        pnlLoaderPenduduk.setPreferredSize(new java.awt.Dimension(455, 477));
        pnlLoaderPenduduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoadingPenduduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoadingPenduduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/giphy (1).gif"))); // NOI18N
        lblLoadingPenduduk.setPreferredSize(new java.awt.Dimension(460, 380));
        pnlLoaderPenduduk.add(lblLoadingPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 640, 300));

        lblLoaderPenduduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoaderPenduduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Loading.png"))); // NOI18N
        pnlLoaderPenduduk.add(lblLoaderPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        getContentPane().add(pnlLoaderPenduduk, "card2");

        pnlMenuPenduduk.setBackground(new java.awt.Color(126, 7, 243));
        pnlMenuPenduduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKK.setBackground(new java.awt.Color(126, 7, 243));
        btnKK.setBorder(null);
        btnKK.setContentAreaFilled(false);
        btnKK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKKMouseExited(evt);
            }
        });
        pnlMenuPenduduk.add(btnKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, 30));

        btnKTP.setBackground(new java.awt.Color(126, 7, 243));
        btnKTP.setBorder(null);
        btnKTP.setContentAreaFilled(false);
        btnKTP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKTPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKTPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKTPMouseExited(evt);
            }
        });
        pnlMenuPenduduk.add(btnKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, 30));

        btnAboutPenduduk.setBackground(new java.awt.Color(126, 7, 243));
        btnAboutPenduduk.setBorder(null);
        btnAboutPenduduk.setContentAreaFilled(false);
        btnAboutPenduduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAboutPenduduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutPendudukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutPendudukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutPendudukMouseExited(evt);
            }
        });
        pnlMenuPenduduk.add(btnAboutPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 140, 30));

        btnLogoutPenduduk.setBackground(new java.awt.Color(126, 7, 243));
        btnLogoutPenduduk.setBorder(null);
        btnLogoutPenduduk.setContentAreaFilled(false);
        btnLogoutPenduduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogoutPenduduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutPendudukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutPendudukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutPendudukMouseExited(evt);
            }
        });
        pnlMenuPenduduk.add(btnLogoutPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 140, 30));

        lblNama.setBackground(new java.awt.Color(126, 7, 243));
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("NAMA");
        pnlMenuPenduduk.add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, 30));

        lblNIK.setBackground(new java.awt.Color(126, 7, 243));
        lblNIK.setForeground(new java.awt.Color(255, 255, 255));
        lblNIK.setText("NIK");
        pnlMenuPenduduk.add(lblNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 30));

        lblArtBoardPenduduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ArtboardPenduduk.png"))); // NOI18N
        pnlMenuPenduduk.add(lblArtBoardPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));

        pnlDashboardPenduduk.setLayout(new java.awt.CardLayout());

        pnlHomePenduduk.setBackground(new java.awt.Color(126, 7, 243));
        pnlHomePenduduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Penduduk.png"))); // NOI18N
        pnlHomePenduduk.add(lblHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pnlDashboardPenduduk.add(pnlHomePenduduk, "card1");

        pnlKTP.setBackground(new java.awt.Color(126, 7, 243));
        pnlKTP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSenin.setBorder(null);
        btnSenin.setContentAreaFilled(false);
        btnSenin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSenin.setPreferredSize(new java.awt.Dimension(130, 40));
        btnSenin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeninMouseClicked(evt);
            }
        });
        pnlKTP.add(btnSenin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnRabu.setBorder(null);
        btnRabu.setContentAreaFilled(false);
        btnRabu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRabu.setPreferredSize(new java.awt.Dimension(130, 40));
        btnRabu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRabuMouseClicked(evt);
            }
        });
        pnlKTP.add(btnRabu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 140, -1));

        btnJumat.setBorder(null);
        btnJumat.setContentAreaFilled(false);
        btnJumat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJumat.setPreferredSize(new java.awt.Dimension(130, 40));
        btnJumat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJumatMouseClicked(evt);
            }
        });
        pnlKTP.add(btnJumat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        lblKTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/KTP.png"))); // NOI18N
        pnlKTP.add(lblKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pnlDashboardPenduduk.add(pnlKTP, "card2");

        pnlKK.setBackground(new java.awt.Color(126, 7, 243));
        pnlKK.setPreferredSize(new java.awt.Dimension(640, 480));
        pnlKK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelasa.setBorder(null);
        btnSelasa.setContentAreaFilled(false);
        btnSelasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelasa.setPreferredSize(new java.awt.Dimension(150, 40));
        btnSelasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelasaMouseClicked(evt);
            }
        });
        pnlKK.add(btnSelasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        btnKamis.setBorder(null);
        btnKamis.setContentAreaFilled(false);
        btnKamis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKamis.setPreferredSize(new java.awt.Dimension(150, 40));
        btnKamis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKamisMouseClicked(evt);
            }
        });
        pnlKK.add(btnKamis, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        lblKK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/KK.png"))); // NOI18N
        lblKK.setText("jLabel1");
        pnlKK.add(lblKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pnlDashboardPenduduk.add(pnlKK, "card3");

        pnlAboutPenduduk.setBackground(new java.awt.Color(126, 7, 243));
        pnlAboutPenduduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAboutPenduduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About.png"))); // NOI18N
        pnlAboutPenduduk.add(lblAboutPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pnlDashboardPenduduk.add(pnlAboutPenduduk, "card4");

        pnlMenuPenduduk.add(pnlDashboardPenduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 460, 480));

        getContentPane().add(pnlMenuPenduduk, "card3");

        pnlLoaderOperator.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoaderOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        pnlLoaderOperator.setMinimumSize(new java.awt.Dimension(460, 480));
        pnlLoaderOperator.setPreferredSize(new java.awt.Dimension(460, 480));
        pnlLoaderOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoadingOperator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoadingOperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/giphy.gif"))); // NOI18N
        pnlLoaderOperator.add(lblLoadingOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 640, 300));

        lblLoaderOperator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoaderOperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Loading.png"))); // NOI18N
        lblLoaderOperator.setPreferredSize(new java.awt.Dimension(455, 477));
        pnlLoaderOperator.add(lblLoaderOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        getContentPane().add(pnlLoaderOperator, "card4");

        pnlMenuOperator.setBackground(new java.awt.Color(126, 7, 243));
        pnlMenuOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAboutOperator.setBorder(null);
        btnAboutOperator.setContentAreaFilled(false);
        btnAboutOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAboutOperator.setPreferredSize(new java.awt.Dimension(130, 30));
        btnAboutOperator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutOperatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutOperatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutOperatorMouseExited(evt);
            }
        });
        pnlMenuOperator.add(btnAboutOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 20));

        btnLogoutOperator.setBorder(null);
        btnLogoutOperator.setContentAreaFilled(false);
        btnLogoutOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogoutOperator.setPreferredSize(new java.awt.Dimension(130, 30));
        btnLogoutOperator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutOperatorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutOperatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutOperatorMouseExited(evt);
            }
        });
        pnlMenuOperator.add(btnLogoutOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 130, 20));

        lblOP.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        lblOP.setForeground(new java.awt.Color(255, 255, 255));
        lblOP.setText("Username");
        lblOP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOP.setPreferredSize(new java.awt.Dimension(110, 30));
        lblOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOPMouseClicked(evt);
            }
        });
        pnlMenuOperator.add(lblOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 110, 30));

        lblArtboardOperator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArtboardOperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ArtboardOperator.png"))); // NOI18N
        lblArtboardOperator.setToolTipText("");
        lblArtboardOperator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlMenuOperator.add(lblArtboardOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 480));

        pnlDashboardOperator.setLayout(new java.awt.CardLayout());

        pnlPanggilan.setBackground(new java.awt.Color(126, 7, 243));
        pnlPanggilan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbNamaHari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Hari", "Senin (KTP)", "Selasa (KK)", "Rabu (KTP)", "Kamis (KK)", "Jumat (KTP)" }));
        cmbNamaHari.setToolTipText("");
        cmbNamaHari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbNamaHari.setPreferredSize(new java.awt.Dimension(370, 26));
        cmbNamaHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNamaHariActionPerformed(evt);
            }
        });
        pnlPanggilan.add(cmbNamaHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 360, 30));

        btnPanggil.setBorder(null);
        btnPanggil.setContentAreaFilled(false);
        btnPanggil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPanggil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanggilMouseClicked(evt);
            }
        });
        pnlPanggilan.add(btnPanggil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 200, 30));

        jScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listArray.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listArray.setEnabled(false);
        jScrollPane.setViewportView(listArray);

        pnlPanggilan.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 360, 260));

        lblPanggilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Operator.png"))); // NOI18N
        pnlPanggilan.add(lblPanggilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pnlDashboardOperator.add(pnlPanggilan, "card1");

        pnlAboutOperator.setBackground(new java.awt.Color(126, 7, 243));
        pnlAboutOperator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAboutOperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About.png"))); // NOI18N
        pnlAboutOperator.add(lblAboutOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 480));

        pnlDashboardOperator.add(pnlAboutOperator, "card2");

        pnlMenuOperator.add(pnlDashboardOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        getContentPane().add(pnlMenuOperator, "card5");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginPendudukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginPendudukMouseClicked
        // TODO add your handling code here:
        pnlLogin.setVisible(true);
        pnlLoginPenduduk.setVisible(true);
        pnlLoginOperator.setVisible(false);
        pnlHomeLogin.setVisible(false);
    }//GEN-LAST:event_btnLoginPendudukMouseClicked

    private void btnLoginOperatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginOperatorMouseClicked
        // TODO add your handling code here:
        pnlLogin.setVisible(true);
        pnlLoginPenduduk.setVisible(false);
        pnlLoginOperator.setVisible(true);
        pnlHomeLogin.setVisible(false);
    }//GEN-LAST:event_btnLoginOperatorMouseClicked

    private void btnLoginPendudukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginPendudukMouseEntered
        // TODO add your handling code here:
        btnLoginPenduduk.setBackground(new Color(129, 76, 181));
        Border b = BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE);
        btnLoginPenduduk.setBorder(b);
    }//GEN-LAST:event_btnLoginPendudukMouseEntered

    private void btnLoginOperatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginOperatorMouseEntered
        // TODO add your handling code here:
        btnLoginOperator.setBackground(new Color(129, 76, 181));
        Border b = BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE);
        btnLoginOperator.setBorder(b);
    }//GEN-LAST:event_btnLoginOperatorMouseEntered

    private void btnLoginPendudukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginPendudukMouseExited
        // TODO add your handling code here:
        btnLoginPenduduk.setBackground(new Color(126, 7, 243));
        Border b = BorderFactory.createMatteBorder(0, 0, 0, 0, (new Color(255, 94, 87)));
        btnLoginPenduduk.setBorder(b);
    }//GEN-LAST:event_btnLoginPendudukMouseExited

    private void btnLoginOperatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginOperatorMouseExited
        // TODO add your handling code here:
        btnLoginOperator.setBackground(new Color(126, 7, 243));
        Border b = BorderFactory.createMatteBorder(0, 0, 0, 0, (new Color(255, 94, 87)));
        btnLoginOperator.setBorder(b);
    }//GEN-LAST:event_btnLoginOperatorMouseExited

    private void btnLoginPendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPendudukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginPendudukActionPerformed

    private void txtNIKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNIKFocusGained
        // TODO add your handling code here:
        txtNIK.setText("");
    }//GEN-LAST:event_txtNIKFocusGained

    private void txtOperatorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOperatorFocusGained
        // TODO add your handling code here:
        txtOperator.setText("");
    }//GEN-LAST:event_txtOperatorFocusGained

    private void pwOperatorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwOperatorFocusGained
        // TODO add your handling code here:
        pwOperator.setText("");
    }//GEN-LAST:event_pwOperatorFocusGained

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        // TODO add your handling code here:
        txtNama.setText("");
    }//GEN-LAST:event_txtNamaFocusGained

    private void btnSubmitOperatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitOperatorMouseClicked
        // TODO add your handling code here:
        if (txtOperator.getText().equalsIgnoreCase("Admin") && pwOperator.getText().equals("kelompok3")) {

            pnlLoaderOperator.show();
            pnlLogin.hide();

            lblOP.setText(this.txtOperator.getText().toUpperCase());
            cmbNamaHari.setSelectedIndex(0);

            new java.util.Timer().schedule(new TimerTask() {

                @Override
                public void run() {

                    pnlMenuOperator.show();

                    pnlLoaderOperator.hide();

                }
            }, 1000 * 3);

        } else {
            JOptionPane.showMessageDialog(null, "Username atau Password salah! Silakan input kembali!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitOperatorMouseClicked

    private void btnSubmitPendudukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitPendudukMouseClicked
        // TODO add your handling code here:
        pnlLoaderPenduduk.show();
        pnlLogin.hide();

        lblNama.setText(this.txtNama.getText());
        lblNIK.setText(this.txtNIK.getText());

        new java.util.Timer().schedule(new TimerTask() {

            @Override
            public void run() {

                pnlMenuPenduduk.show();

                pnlLoaderPenduduk.hide();

            }
        }, 1000 * 3);

    }//GEN-LAST:event_btnSubmitPendudukMouseClicked

    private void txtNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusLost
        // TODO add your handling code here:
        String kosong = txtNama.getText();

        if (kosong.equals("")) {
            txtNama.setText("Nama Lengkap");
        }
    }//GEN-LAST:event_txtNamaFocusLost

    private void txtNIKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNIKFocusLost
        // TODO add your handling code here:
        String kosong = txtNIK.getText();

        if (kosong.equals("")) {
            txtNIK.setText("NIK");
        }
    }//GEN-LAST:event_txtNIKFocusLost

    private void txtOperatorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOperatorFocusLost
        // TODO add your handling code here:
        String kosong = txtOperator.getText();

        if (kosong.equals("")) {
            txtOperator.setText("Username");
        }
    }//GEN-LAST:event_txtOperatorFocusLost

    private void pwOperatorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwOperatorFocusLost
        // TODO add your handling code here:
        String kosong = pwOperator.getText();

        if (kosong.equals("")) {
            pwOperator.setText("Password");
        }
    }//GEN-LAST:event_pwOperatorFocusLost

    private void btnKKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKKMouseClicked
        // TODO add your handling code here:
        pnlMenuPenduduk.setVisible(true);
        pnlHomePenduduk.setVisible(false);
        pnlKK.setVisible(true);
        pnlKTP.setVisible(false);
        pnlAboutPenduduk.setVisible(false);
    }//GEN-LAST:event_btnKKMouseClicked

    private void btnKKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKKMouseEntered
        // TODO add your handling code here:
        btnKK.setBackground(new Color(129, 76, 181));
        Border b = BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE);
        btnKK.setBorder(b);
    }//GEN-LAST:event_btnKKMouseEntered

    private void btnKKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKKMouseExited
        // TODO add your handling code here:
        btnKK.setBackground(new Color(126, 7, 243));
        Border b = BorderFactory.createMatteBorder(0, 0, 0, 0, (new Color(255, 94, 87)));
        btnKK.setBorder(b);
    }//GEN-LAST:event_btnKKMouseExited

    private void btnKTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKTPMouseClicked
        // TODO add your handling code here:
        pnlMenuPenduduk.setVisible(true);
        pnlHomePenduduk.setVisible(false);
        pnlKK.setVisible(false);
        pnlKTP.setVisible(true);
        pnlAboutPenduduk.setVisible(false);
    }//GEN-LAST:event_btnKTPMouseClicked

    private void btnKTPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKTPMouseEntered
        // TODO add your handling code here:
        btnKTP.setBackground(new Color(129, 76, 181));
        Border b = BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE);
        btnKTP.setBorder(b);
    }//GEN-LAST:event_btnKTPMouseEntered

    private void btnKTPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKTPMouseExited
        // TODO add your handling code here:
        btnKTP.setBackground(new Color(126, 7, 243));
        Border b = BorderFactory.createMatteBorder(0, 0, 0, 0, (new Color(255, 94, 87)));
        btnKTP.setBorder(b);
    }//GEN-LAST:event_btnKTPMouseExited

    private void btnAboutPendudukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutPendudukMouseClicked
        // TODO add your handling code here:
        pnlMenuPenduduk.setVisible(true);
        pnlHomePenduduk.setVisible(false);
        pnlKK.setVisible(false);
        pnlKTP.setVisible(false);
        pnlAboutPenduduk.setVisible(true);
    }//GEN-LAST:event_btnAboutPendudukMouseClicked

    private void btnAboutPendudukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutPendudukMouseEntered
        // TODO add your handling code here:
        btnAboutPenduduk.setBackground(new Color(129, 76, 181));
        Border b = BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE);
        btnAboutPenduduk.setBorder(b);
    }//GEN-LAST:event_btnAboutPendudukMouseEntered

    private void btnAboutPendudukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutPendudukMouseExited
        // TODO add your handling code here:
        btnAboutPenduduk.setBackground(new Color(126, 7, 243));
        Border b = BorderFactory.createMatteBorder(0, 0, 0, 0, (new Color(255, 94, 87)));
        btnAboutPenduduk.setBorder(b);
    }//GEN-LAST:event_btnAboutPendudukMouseExited

    private void btnLogoutPendudukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPendudukMouseClicked
        // TODO add your handling code here:
        pnlMenuPenduduk.hide();
        pnlLogin.show();
        txtNama.setText("Nama Lengkap");
        txtNIK.setText("NIK");
    }//GEN-LAST:event_btnLogoutPendudukMouseClicked

    private void btnLogoutPendudukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPendudukMouseEntered
        // TODO add your handling code here:
        btnLogoutPenduduk.setBackground(new Color(129, 76, 181));
        Border b = BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE);
        btnLogoutPenduduk.setBorder(b);
    }//GEN-LAST:event_btnLogoutPendudukMouseEntered

    private void btnLogoutPendudukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPendudukMouseExited
        // TODO add your handling code here:
        btnLogoutPenduduk.setBackground(new Color(126, 7, 243));
        Border b = BorderFactory.createMatteBorder(0, 0, 0, 0, (new Color(255, 94, 87)));
        btnLogoutPenduduk.setBorder(b);
    }//GEN-LAST:event_btnLogoutPendudukMouseExited

    private void btnSeninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeninMouseClicked
        // TODO add your handling code here:
        Tiket t = new Tiket();

        WaktuDaftar = LocalDateTime.now();
        dtf = DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy HH:mm");

        t.show();
        t.pnlTiketKTP.setVisible(true);
        t.pnlTiketKK.setVisible(false);

        t.lblNamaA.setText(this.lblNama.getText());
        t.lblNIKA.setText(this.lblNIK.getText());
        t.lblWaktuDaftarKTP.setText(WaktuDaftar.format(dtf));
        t.lblWaktuBuatKTP.setText("Senin di pekan berikutnya setelah pendaftaran");

        boolean check = isFull(tailSenin);
        if (check) {
            JOptionPane.showMessageDialog(null, "ANTRIAN PENUH! Silakan pilih hari lain!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            tailSenin++;
            dataSenin[tailSenin] = this.lblNama.getText();
            JOptionPane.showMessageDialog(null, "Data telah dimasukkan ke dalam antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
            listArray.setListData(dataSenin);
        }
    }//GEN-LAST:event_btnSeninMouseClicked

    private void btnRabuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRabuMouseClicked
        // TODO add your handling code here:
        Tiket t = new Tiket();

        WaktuDaftar = LocalDateTime.now();
        dtf = DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy HH:mm");

        t.show();
        t.pnlTiketKTP.setVisible(true);
        t.pnlTiketKK.setVisible(false);

        t.lblNamaA.setText(this.lblNama.getText());
        t.lblNIKA.setText(this.lblNIK.getText());
        t.lblWaktuDaftarKTP.setText(WaktuDaftar.format(dtf));
        t.lblWaktuBuatKTP.setText("Rabu di pekan berikutnya setelah pendaftaran");

        boolean check = isFull(tailRabu);
        if (check) {
            JOptionPane.showMessageDialog(null, "ANTRIAN PENUH! Silakan pilih hari lain!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            tailRabu++;
            dataRabu[tailRabu] = this.lblNama.getText();
            JOptionPane.showMessageDialog(null, "Data telah dimasukkan ke dalam antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
            listArray.setListData(dataRabu);
        }
    }//GEN-LAST:event_btnRabuMouseClicked

    private void btnJumatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJumatMouseClicked
        // TODO add your handling code here:
        Tiket t = new Tiket();

        WaktuDaftar = LocalDateTime.now();
        dtf = DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy HH:mm");

        t.show();
        t.pnlTiketKTP.setVisible(true);
        t.pnlTiketKK.setVisible(false);

        t.lblNamaA.setText(this.lblNama.getText());
        t.lblNIKA.setText(this.lblNIK.getText());
        t.lblWaktuDaftarKTP.setText(WaktuDaftar.format(dtf));
        t.lblWaktuBuatKTP.setText("Jum'at di pekan berikutnya setelah pendaftaran");

        boolean check = isFull(tailJumat);
        if (check) {
            JOptionPane.showMessageDialog(null, "ANTRIAN PENUH! Silakan pilih hari lain!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            tailJumat++;
            dataJumat[tailJumat] = this.lblNama.getText();
            JOptionPane.showMessageDialog(null, "Data telah dimasukkan ke dalam antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
            listArray.setListData(dataJumat);
        }
    }//GEN-LAST:event_btnJumatMouseClicked

    private void btnSelasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelasaMouseClicked
        // TODO add your handling code here:
        Tiket t = new Tiket();

        WaktuDaftar = LocalDateTime.now();
        dtf = DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy HH:mm");

        t.show();
        t.pnlTiketKTP.setVisible(false);
        t.pnlTiketKK.setVisible(true);

        t.lblNamaB.setText(this.lblNama.getText());
        t.lblNIKB.setText(this.lblNIK.getText());
        t.lblWaktuDaftarKK.setText(WaktuDaftar.format(dtf));
        t.lblWaktuBuatKK.setText("Selasa di pekan berikutnya setelah pendaftaran");

        boolean check = isFull(tailSelasa);
        if (check) {
            JOptionPane.showMessageDialog(null, "ANTRIAN PENUH! Silakan pilih hari lain!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            tailSelasa++;
            dataSelasa[tailSelasa] = this.lblNama.getText();
            JOptionPane.showMessageDialog(null, "Data telah dimasukkan ke dalam antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
            listArray.setListData(dataSelasa);
        }
    }//GEN-LAST:event_btnSelasaMouseClicked

    private void btnKamisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKamisMouseClicked
        // TODO add your handling code here:
        Tiket t = new Tiket();

        WaktuDaftar = LocalDateTime.now();
        dtf = DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy HH:mm");

        t.show();
        t.pnlTiketKTP.setVisible(false);
        t.pnlTiketKK.setVisible(true);

        t.lblNamaB.setText(this.lblNama.getText());
        t.lblNIKB.setText(this.lblNIK.getText());
        t.lblWaktuDaftarKK.setText(WaktuDaftar.format(dtf));
        t.lblWaktuBuatKK.setText("Kamis di pekan berikutnya setelah pendaftaran");

        boolean check = isFull(tailKamis);
        if (check) {
            JOptionPane.showMessageDialog(null, "ANTRIAN PENUH! Silakan pilih hari lain!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            tailKamis++;
            dataKamis[tailKamis] = this.lblNama.getText();
            JOptionPane.showMessageDialog(null, "Data telah dimasukkan ke dalam antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
            listArray.setListData(dataKamis);
        }
    }//GEN-LAST:event_btnKamisMouseClicked

    private void btnAboutOperatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutOperatorMouseClicked
        // TODO add your handling code here
        pnlMenuOperator.setVisible(true);
        pnlAboutOperator.setVisible(true);
        pnlPanggilan.setVisible(false);
    }//GEN-LAST:event_btnAboutOperatorMouseClicked

    private void btnAboutOperatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutOperatorMouseEntered
        // TODO add your handling code here:
        btnAboutOperator.setBackground(new Color(129, 76, 181));
        Border b = BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE);
        btnAboutOperator.setBorder(b);
    }//GEN-LAST:event_btnAboutOperatorMouseEntered

    private void btnAboutOperatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutOperatorMouseExited
        // TODO add your handling code here:
        btnAboutOperator.setBackground(new Color(126, 7, 243));
        Border b = BorderFactory.createMatteBorder(0, 0, 0, 0, (new Color(255, 94, 87)));
        btnAboutOperator.setBorder(b);
    }//GEN-LAST:event_btnAboutOperatorMouseExited

    private void btnLogoutOperatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutOperatorMouseClicked
        // TODO add your handling code here:
        pnlMenuOperator.hide();
        pnlLogin.show();
        txtOperator.setText("Username");
        pwOperator.setText("Password");
    }//GEN-LAST:event_btnLogoutOperatorMouseClicked

    private void btnLogoutOperatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutOperatorMouseEntered
        // TODO add your handling code here:
        btnLogoutOperator.setBackground(new Color(129, 76, 181));
        Border b = BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE);
        btnLogoutOperator.setBorder(b);
    }//GEN-LAST:event_btnLogoutOperatorMouseEntered

    private void btnLogoutOperatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutOperatorMouseExited
        // TODO add your handling code here:
        btnLogoutOperator.setBackground(new Color(126, 7, 243));
        Border b = BorderFactory.createMatteBorder(0, 0, 0, 0, (new Color(255, 94, 87)));
        btnLogoutOperator.setBorder(b);
    }//GEN-LAST:event_btnLogoutOperatorMouseExited

    private void cmbNamaHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNamaHariActionPerformed
        // TODO add your handling code here:
        String[] kosong = {"Silakan pilih hari untuk menampilkan data!"};
        switch (cmbNamaHari.getSelectedIndex()) {
            case 0:
                listArray.setListData(kosong);
                break;
            case 1:
                listArray.setListData(dataSenin);
                break;
            case 2:
                listArray.setListData(dataSelasa);
                break;
            case 3:
                listArray.setListData(dataRabu);
                break;
            case 4:
                listArray.setListData(dataKamis);
                break;
            case 5:
                listArray.setListData(dataJumat);
                break;
        }
    }//GEN-LAST:event_cmbNamaHariActionPerformed

    private void btnPanggilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanggilMouseClicked
        // TODO add your handling code here:
        boolean check;
        switch (cmbNamaHari.getSelectedIndex()) {
            case 0:
                break;
            case 1:
                check = isEmpty(tailSenin);
                if (check) {
                    JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    dataSenin[1] = null;
                    for (int i = 1; i < tailSenin; i++) {
                        dataSenin[i] = dataSenin[i + 1];
                    }
                    dataSenin[tailSenin] = null;
                    tailSenin--;
                    JOptionPane.showMessageDialog(null, "Data telah dikeluarkan dari antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
                    listArray.setListData(dataSenin);
                }
                break;
            case 2:
                check = isEmpty(tailSelasa);
                if (check) {
                    JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    dataSelasa[1] = null;
                    for (int i = 1; i < tailSelasa; i++) {
                        dataSelasa[i] = dataSelasa[i + 1];
                    }
                    dataSelasa[tailSelasa] = null;
                    tailSelasa--;
                    JOptionPane.showMessageDialog(null, "Data telah dikeluarkan dari antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
                    listArray.setListData(dataSelasa);
                }
                break;
            case 3:
                check = isEmpty(tailRabu);
                if (check) {
                    JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    dataRabu[1] = null;
                    for (int i = 1; i < tailRabu; i++) {
                        dataRabu[i] = dataRabu[i + 1];
                    }
                    dataRabu[tailRabu] = null;
                    tailRabu--;
                    JOptionPane.showMessageDialog(null, "Data telah dikeluarkan dari antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
                    listArray.setListData(dataRabu);
                }
                break;
            case 4:
                check = isEmpty(tailKamis);
                if (check) {
                    JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    dataKamis[1] = null;
                    for (int i = 1; i < tailKamis; i++) {
                        dataKamis[i] = dataKamis[i + 1];
                    }
                    dataKamis[tailKamis] = null;
                    tailKamis--;
                    JOptionPane.showMessageDialog(null, "Data telah dikeluarkan dari antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
                    listArray.setListData(dataKamis);
                }
                break;
            case 5:
                check = isEmpty(tailJumat);
                if (check) {
                    JOptionPane.showMessageDialog(null, "ANTRIAN KOSONG!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    dataJumat[1] = null;
                    for (int i = 1; i < tailJumat; i++) {
                        dataJumat[i] = dataJumat[i + 1];
                    }
                    dataJumat[tailJumat] = null;
                    tailJumat--;
                    JOptionPane.showMessageDialog(null, "Data telah dikeluarkan dari antrian!", "Information", JOptionPane.INFORMATION_MESSAGE);
                    listArray.setListData(dataJumat);
                }
                break;
        }

    }//GEN-LAST:event_btnPanggilMouseClicked

    private void lblOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOPMouseClicked
        // TODO add your handling code here:
        pnlMenuOperator.setVisible(true);
        pnlAboutOperator.setVisible(false);
        pnlPanggilan.setVisible(true);
    }//GEN-LAST:event_lblOPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutOperator;
    private javax.swing.JButton btnAboutPenduduk;
    private javax.swing.JButton btnJumat;
    private javax.swing.JButton btnKK;
    private javax.swing.JButton btnKTP;
    private javax.swing.JButton btnKamis;
    private javax.swing.JButton btnLoginOperator;
    private javax.swing.JButton btnLoginPenduduk;
    private javax.swing.JButton btnLogoutOperator;
    private javax.swing.JButton btnLogoutPenduduk;
    private javax.swing.JButton btnPanggil;
    private javax.swing.JButton btnRabu;
    private javax.swing.JButton btnSelasa;
    private javax.swing.JButton btnSenin;
    private javax.swing.JButton btnSubmitOperator;
    private javax.swing.JButton btnSubmitPenduduk;
    public javax.swing.JComboBox cmbNamaHari;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblAboutOperator;
    private javax.swing.JLabel lblAboutPenduduk;
    private javax.swing.JLabel lblArtBoardPenduduk;
    private javax.swing.JLabel lblArtboard;
    private javax.swing.JLabel lblArtboardOperator;
    private javax.swing.JLabel lblHome1;
    private javax.swing.JLabel lblHomeLogin;
    private javax.swing.JLabel lblKK;
    private javax.swing.JLabel lblKTP;
    private javax.swing.JLabel lblLoaderOperator;
    private javax.swing.JLabel lblLoaderPenduduk;
    private javax.swing.JLabel lblLoadingOperator;
    private javax.swing.JLabel lblLoadingPenduduk;
    private javax.swing.JLabel lblLoginOperator;
    private javax.swing.JLabel lblLoginPenduduk;
    public javax.swing.JLabel lblNIK;
    public javax.swing.JLabel lblNama;
    public javax.swing.JLabel lblOP;
    private javax.swing.JLabel lblPanggilan;
    public javax.swing.JList listArray;
    private javax.swing.JPanel pnlAboutOperator;
    private javax.swing.JPanel pnlAboutPenduduk;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDashboardOperator;
    private javax.swing.JPanel pnlDashboardPenduduk;
    private javax.swing.JPanel pnlHomeLogin;
    private javax.swing.JPanel pnlHomePenduduk;
    private javax.swing.JPanel pnlKK;
    private javax.swing.JPanel pnlKTP;
    private javax.swing.JPanel pnlLoaderOperator;
    private javax.swing.JPanel pnlLoaderPenduduk;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLoginOperator;
    private javax.swing.JPanel pnlLoginPenduduk;
    private javax.swing.JPanel pnlMenuOperator;
    private javax.swing.JPanel pnlMenuPenduduk;
    private javax.swing.JPanel pnlPanggilan;
    private javax.swing.JPasswordField pwOperator;
    public javax.swing.JTextField txtNIK;
    public javax.swing.JTextField txtNama;
    public javax.swing.JTextField txtOperator;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }
}
