/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;

import java.awt.Toolkit;

/**
 *
 * @author Fachridan Tio Mu'afa
 */
public class Tiket extends javax.swing.JFrame {

    /**
     * Creates new form Tiket
     */
    public Tiket() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTiketKTP = new javax.swing.JPanel();
        lblNamaA = new javax.swing.JLabel();
        lblNIKA = new javax.swing.JLabel();
        lblWaktuDaftarKTP = new javax.swing.JLabel();
        lblWaktuBuatKTP = new javax.swing.JLabel();
        lblTIketKTP = new javax.swing.JLabel();
        pnlTiketKK = new javax.swing.JPanel();
        lblNamaB = new javax.swing.JLabel();
        lblNIKB = new javax.swing.JLabel();
        lblWaktuDaftarKK = new javax.swing.JLabel();
        lblWaktuBuatKK = new javax.swing.JLabel();
        lblTIketKK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Smart Villager");
        setMaximizedBounds(new java.awt.Rectangle(250, 150, 640, 480));
        setMinimumSize(new java.awt.Dimension(620, 180));
        setName("frame5"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(620, 180));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlTiketKTP.setBackground(new java.awt.Color(126, 7, 243));
        pnlTiketKTP.setMaximumSize(new java.awt.Dimension(640, 480));
        pnlTiketKTP.setOpaque(false);
        pnlTiketKTP.setPreferredSize(new java.awt.Dimension(620, 180));
        pnlTiketKTP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaA.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        pnlTiketKTP.add(lblNamaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 240, 20));

        lblNIKA.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        pnlTiketKTP.add(lblNIKA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 20));

        lblWaktuDaftarKTP.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        pnlTiketKTP.add(lblWaktuDaftarKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 240, 20));

        lblWaktuBuatKTP.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        pnlTiketKTP.add(lblWaktuBuatKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 240, 20));

        lblTIketKTP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTIketKTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tiket KTP.png"))); // NOI18N
        lblTIketKTP.setLabelFor(lblTIketKTP);
        lblTIketKTP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTIketKTP.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTIketKTP.setPreferredSize(new java.awt.Dimension(620, 180));
        pnlTiketKTP.add(lblTIketKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        lblTIketKTP.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnlTiketKTP, "card1");

        pnlTiketKK.setBackground(new java.awt.Color(126, 7, 243));
        pnlTiketKK.setMaximumSize(new java.awt.Dimension(640, 480));
        pnlTiketKK.setMinimumSize(new java.awt.Dimension(620, 180));
        pnlTiketKK.setOpaque(false);
        pnlTiketKK.setPreferredSize(new java.awt.Dimension(620, 180));
        pnlTiketKK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaB.setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        pnlTiketKK.add(lblNamaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 240, 20));

        lblNIKB.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        pnlTiketKK.add(lblNIKB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 20));

        lblWaktuDaftarKK.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        pnlTiketKK.add(lblWaktuDaftarKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 240, 20));

        lblWaktuBuatKK.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        pnlTiketKK.add(lblWaktuBuatKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 132, 240, 20));

        lblTIketKK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTIketKK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tiket KK.png"))); // NOI18N
        lblTIketKK.setLabelFor(pnlTiketKK);
        lblTIketKK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTIketKK.setMinimumSize(new java.awt.Dimension(0, 0));
        lblTIketKK.setPreferredSize(new java.awt.Dimension(620, 180));
        pnlTiketKK.add(lblTIketKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        getContentPane().add(pnlTiketKK, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tiket().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblNIKA;
    public javax.swing.JLabel lblNIKB;
    public javax.swing.JLabel lblNamaA;
    public javax.swing.JLabel lblNamaB;
    private javax.swing.JLabel lblTIketKK;
    private javax.swing.JLabel lblTIketKTP;
    public javax.swing.JLabel lblWaktuBuatKK;
    public javax.swing.JLabel lblWaktuBuatKTP;
    public javax.swing.JLabel lblWaktuDaftarKK;
    public javax.swing.JLabel lblWaktuDaftarKTP;
    public javax.swing.JPanel pnlTiketKK;
    public javax.swing.JPanel pnlTiketKTP;
    // End of variables declaration//GEN-END:variables
}
